# Generated by Django 5.0.7 on 2024-08-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bastakora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='alobom',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='artest',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='songs',
            options={'ordering': ['id']},
        ),
    ]
